services:
  iptv-api:
    image: guovern/iptv-api:latest
    container_name: iptv-api
    restart: unless-stopped
    tty: true
    stdin_open: true

    volumes:
      - /iptv-api/config:/iptv-api/config
      - /iptv-api/output:/iptv-api/output

    environment:
      CDN_URL: ""
      HTTP_PROXY: ""