CREATE TABLE IF NOT EXISTS public.v_channel (
	id character varying(255) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	title character varying(255) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	code character varying(255) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	pic character varying(255) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	status integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	create_time timestamp without time zone GENERATED BY DEFAULT AS IDENTITY,
	update_time timestamp without time zone GENERATED BY DEFAULT AS IDENTITY,
	channel_group character varying(255) GENERATED BY DEFAULT AS IDENTITY,
	url jsonb GENERATED BY DEFAULT AS IDENTITY,
	url_ip6 jsonb GENERATED BY DEFAULT AS IDENTITY,
	PRIMARY KEY(id)
);